/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations["register_api_v1_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations["get_me_api_v1_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/regulatory/authorities/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Authorities */
    get: operations["list_authorities_api_v1_regulatory_authorities__get"];
    put?: never;
    /** Create Authority */
    post: operations["create_authority_api_v1_regulatory_authorities__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/regulatory/authorities/{authority_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Authority */
    get: operations["get_authority_api_v1_regulatory_authorities__authority_id__get"];
    put?: never;
    post?: never;
    /** Delete Authority */
    delete: operations["delete_authority_api_v1_regulatory_authorities__authority_id__delete"];
    options?: never;
    head?: never;
    /** Update Authority */
    patch: operations["update_authority_api_v1_regulatory_authorities__authority_id__patch"];
    trace?: never;
  };
  "/api/v1/regulatory/sources/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sources */
    get: operations["list_sources_api_v1_regulatory_sources__get"];
    put?: never;
    /** Create Source */
    post: operations["create_source_api_v1_regulatory_sources__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/regulatory/sources/{source_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Source */
    get: operations["get_source_api_v1_regulatory_sources__source_id__get"];
    put?: never;
    post?: never;
    /** Delete Source */
    delete: operations["delete_source_api_v1_regulatory_sources__source_id__delete"];
    options?: never;
    head?: never;
    /** Update Source */
    patch: operations["update_source_api_v1_regulatory_sources__source_id__patch"];
    trace?: never;
  };
  "/api/v1/regulatory/sources/{source_id}/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run Source */
    post: operations["run_source_api_v1_regulatory_sources__source_id__run_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/regulatory/sources/{source_id}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Source Runs */
    get: operations["list_source_runs_api_v1_regulatory_sources__source_id__runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/regulatory/sources/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Run */
    get: operations["get_run_api_v1_regulatory_sources_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/regulatory/documents/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Document */
    post: operations["upload_document_api_v1_regulatory_documents_upload_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/regulatory/documents/{document_id}/process": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Trigger Document Processing */
    post: operations["trigger_document_processing_api_v1_regulatory_documents__document_id__process_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/regulatory/documents/{document_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Document Status */
    get: operations["get_document_status_api_v1_regulatory_documents__document_id__status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/regulatory/documents/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Documents */
    get: operations["list_documents_api_v1_regulatory_documents__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/regulatory/documents/{document_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Document */
    get: operations["get_document_api_v1_regulatory_documents__document_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/portfolio/products/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Products */
    get: operations["list_products_api_v1_portfolio_products__get"];
    put?: never;
    /** Create Product */
    post: operations["create_product_api_v1_portfolio_products__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/portfolio/products/{product_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Product */
    get: operations["get_product_api_v1_portfolio_products__product_id__get"];
    put?: never;
    post?: never;
    /** Delete Product */
    delete: operations["delete_product_api_v1_portfolio_products__product_id__delete"];
    options?: never;
    head?: never;
    /** Update Product */
    patch: operations["update_product_api_v1_portfolio_products__product_id__patch"];
    trace?: never;
  };
  "/api/v1/portfolio/markets/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Markets */
    get: operations["list_markets_api_v1_portfolio_markets__get"];
    put?: never;
    /** Create Market */
    post: operations["create_market_api_v1_portfolio_markets__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/portfolio/markets/{market_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Market */
    get: operations["get_market_api_v1_portfolio_markets__market_id__get"];
    put?: never;
    post?: never;
    /** Delete Market */
    delete: operations["delete_market_api_v1_portfolio_markets__market_id__delete"];
    options?: never;
    head?: never;
    /** Update Market */
    patch: operations["update_market_api_v1_portfolio_markets__market_id__patch"];
    trace?: never;
  };
  "/api/v1/portfolio/processes/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Processes */
    get: operations["list_processes_api_v1_portfolio_processes__get"];
    put?: never;
    /** Create Process */
    post: operations["create_process_api_v1_portfolio_processes__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/portfolio/processes/{process_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Process */
    get: operations["get_process_api_v1_portfolio_processes__process_id__get"];
    put?: never;
    post?: never;
    /** Delete Process */
    delete: operations["delete_process_api_v1_portfolio_processes__process_id__delete"];
    options?: never;
    head?: never;
    /** Update Process */
    patch: operations["update_process_api_v1_portfolio_processes__process_id__patch"];
    trace?: never;
  };
  "/api/v1/portfolio/controls/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Controls */
    get: operations["list_controls_api_v1_portfolio_controls__get"];
    put?: never;
    /** Create Control */
    post: operations["create_control_api_v1_portfolio_controls__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/portfolio/controls/{control_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Control */
    get: operations["get_control_api_v1_portfolio_controls__control_id__get"];
    put?: never;
    post?: never;
    /** Delete Control */
    delete: operations["delete_control_api_v1_portfolio_controls__control_id__delete"];
    options?: never;
    head?: never;
    /** Update Control */
    patch: operations["update_control_api_v1_portfolio_controls__control_id__patch"];
    trace?: never;
  };
  "/api/v1/portfolio/registrations/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Registrations */
    get: operations["list_registrations_api_v1_portfolio_registrations__get"];
    put?: never;
    /** Create Registration */
    post: operations["create_registration_api_v1_portfolio_registrations__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/portfolio/registrations/{registration_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Registration */
    get: operations["get_registration_api_v1_portfolio_registrations__registration_id__get"];
    put?: never;
    post?: never;
    /** Delete Registration */
    delete: operations["delete_registration_api_v1_portfolio_registrations__registration_id__delete"];
    options?: never;
    head?: never;
    /** Update Registration */
    patch: operations["update_registration_api_v1_portfolio_registrations__registration_id__patch"];
    trace?: never;
  };
  "/api/v1/impact/analyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Analyze Impact
     * @description Trigger or fetch portfolio impact analysis for a given regulatory change.
     *     Executes hybrid deterministic + AI matching.
     */
    post: operations["analyze_impact_api_v1_impact_analyze_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/impact/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Impact Assessments */
    get: operations["list_impact_assessments_api_v1_impact__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/impact/{assessment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Impact Assessment */
    get: operations["get_impact_assessment_api_v1_impact__assessment_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/impact/{assessment_id}/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Assessment Items */
    get: operations["list_assessment_items_api_v1_impact__assessment_id__items_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/impact/{assessment_id}/reanalyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reanalyze Impact */
    post: operations["reanalyze_impact_api_v1_impact__assessment_id__reanalyze_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate Report */
    post: operations["generate_report_api_v1_reports_generate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Reports */
    get: operations["list_reports_api_v1_reports__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports/{report_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Report */
    get: operations["get_report_api_v1_reports__report_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports/{report_id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Report Versions */
    get: operations["list_report_versions_api_v1_reports__report_id__versions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness Check */
    get: operations["readiness_check_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness Check */
    get: operations["liveness_check_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AuthorityCreate */
    AuthorityCreate: {
      /** Name */
      name: string;
      /** Short Name */
      short_name: string;
      /** Jurisdiction */
      jurisdiction?: string | null;
      /** Country */
      country?: string | null;
      /** Website */
      website?: string | null;
      /** Description */
      description?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active: boolean;
    };
    /** AuthorityResponse */
    AuthorityResponse: {
      /** Name */
      name: string;
      /** Short Name */
      short_name: string;
      /** Jurisdiction */
      jurisdiction?: string | null;
      /** Country */
      country?: string | null;
      /** Website */
      website?: string | null;
      /** Description */
      description?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active: boolean;
      /** Id */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** AuthorityUpdate */
    AuthorityUpdate: {
      /** Name */
      name?: string | null;
      /** Short Name */
      short_name?: string | null;
      /** Jurisdiction */
      jurisdiction?: string | null;
      /** Country */
      country?: string | null;
      /** Website */
      website?: string | null;
      /** Description */
      description?: string | null;
      /** Is Active */
      is_active?: boolean | null;
    };
    /** Body_login_api_v1_auth_login_post */
    Body_login_api_v1_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** Body_register_api_v1_auth_register_post */
    Body_register_api_v1_auth_register_post: {
      user_in: components["schemas"]["UserCreate"];
      org_in: components["schemas"]["OrganizationCreate"];
    };
    /** Body_upload_document_api_v1_regulatory_documents_upload_post */
    Body_upload_document_api_v1_regulatory_documents_upload_post: {
      /** File */
      file: string;
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /**
       * Document Type
       * @default OTHER
       */
      document_type: string;
      /** Jurisdiction */
      jurisdiction?: string | null;
      /** Country */
      country?: string | null;
      /** Source Url */
      source_url?: string | null;
      /** Authority Id */
      authority_id: string;
      /** Source Id */
      source_id: string;
    };
    /**
     * ConnectorType
     * @enum {string}
     */
    ConnectorType: "RSS" | "API" | "WEB_SERVICE" | "HTML" | "DOCUMENT";
    /**
     * ControlCategory
     * @enum {string}
     */
    ControlCategory:
      | "QUALITY"
      | "SAFETY"
      | "REGULATORY"
      | "CYBERSECURITY"
      | "DATA"
      | "MANUFACTURING"
      | "LABELING"
      | "CLINICAL"
      | "RISK"
      | "OTHER";
    /** ControlCreate */
    ControlCreate: {
      /** Product Id */
      product_id?: string | null;
      /** Process Id */
      process_id?: string | null;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** @default OTHER */
      category: components["schemas"]["ControlCategory"];
      /** Owner */
      owner?: string | null;
      /** @default ACTIVE */
      status: components["schemas"]["ControlStatus"];
    };
    /** ControlResponse */
    ControlResponse: {
      /** Product Id */
      product_id?: string | null;
      /** Process Id */
      process_id?: string | null;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** @default OTHER */
      category: components["schemas"]["ControlCategory"];
      /** Owner */
      owner?: string | null;
      /** @default ACTIVE */
      status: components["schemas"]["ControlStatus"];
      /** Id */
      id: string;
      /** Organization Id */
      organization_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ControlStatus
     * @enum {string}
     */
    ControlStatus: "ACTIVE" | "INACTIVE" | "DRAFT";
    /** ControlUpdate */
    ControlUpdate: {
      /** Product Id */
      product_id?: string | null;
      /** Process Id */
      process_id?: string | null;
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      category?: components["schemas"]["ControlCategory"] | null;
      /** Owner */
      owner?: string | null;
      status?: components["schemas"]["ControlStatus"] | null;
    };
    /**
     * DocumentProcessingStatus
     * @enum {string}
     */
    DocumentProcessingStatus:
      | "DISCOVERED"
      | "DOWNLOADING"
      | "DOWNLOADED"
      | "PARSING"
      | "PARSED"
      | "ANALYZING"
      | "ANALYZED"
      | "FAILED";
    /** DocumentResponse */
    DocumentResponse: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /** @default OTHER */
      document_type: components["schemas"]["DocumentType"];
      /** Jurisdiction */
      jurisdiction?: string | null;
      /** Country */
      country?: string | null;
      /** Source Url */
      source_url?: string | null;
      /** Id */
      id: string;
      /** Organization Id */
      organization_id: string;
      /** Authority Id */
      authority_id: string;
      /** Source Id */
      source_id: string;
      /** Storage Key */
      storage_key?: string | null;
      /** Mime Type */
      mime_type?: string | null;
      /** File Size */
      file_size?: number | null;
      /** Sha256 */
      sha256?: string | null;
      /** Publication Date */
      publication_date?: string | null;
      /** Effective Date */
      effective_date?: string | null;
      /**
       * Retrieved At
       * Format: date-time
       */
      retrieved_at: string;
      processing_status: components["schemas"]["DocumentProcessingStatus"];
      /**
       * Language
       * @default en
       */
      language: string;
      /** Extracted Text */
      extracted_text?: string | null;
      /** Parsed At */
      parsed_at?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * DocumentType
     * @enum {string}
     */
    DocumentType:
      | "REGULATION"
      | "GUIDANCE"
      | "NOTICE"
      | "SAFETY_ALERT"
      | "STANDARD"
      | "AMENDMENT"
      | "RULE"
      | "DRAFT"
      | "FINAL"
      | "OTHER";
    /** DocumentUploadResponse */
    DocumentUploadResponse: {
      /** Document Id */
      document_id: string;
      /** Sha256 */
      sha256: string;
      /** Message */
      message: string;
      /**
       * Is Duplicate
       * @default false
       */
      is_duplicate: boolean;
    };
    /**
     * EntityType
     * @enum {string}
     */
    EntityType: "PRODUCT" | "MARKET" | "PROCESS" | "CONTROL" | "REGISTRATION";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ImpactAssessmentCreate */
    ImpactAssessmentCreate: {
      /** Regulatory Change Id */
      regulatory_change_id: string;
      /**
       * Force Reanalyze
       * @default false
       */
      force_reanalyze: boolean;
    };
    /** ImpactAssessmentResponse */
    ImpactAssessmentResponse: {
      /** Regulatory Change Id */
      regulatory_change_id: string;
      /** @default PENDING */
      status: components["schemas"]["ImpactAssessmentStatus"];
      /** @default REQUIRES_REVIEW */
      overall_impact_level: components["schemas"]["ImpactLevel"];
      /**
       * Overall Confidence
       * @default 0.85
       */
      overall_confidence: number;
      /** Summary */
      summary?: string | null;
      /**
       * Analysis Version
       * @default 1
       */
      analysis_version: number;
      /** Id */
      id: string;
      /** Organization Id */
      organization_id: string;
      /** Engine Version */
      engine_version?: string | null;
      /** Ai Model */
      ai_model?: string | null;
      /** Prompt Version */
      prompt_version?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at?: string | null;
      /**
       * Items
       * @default []
       */
      items: components["schemas"]["ImpactItemResponse"][];
    };
    /**
     * ImpactAssessmentStatus
     * @enum {string}
     */
    ImpactAssessmentStatus:
      | "PENDING"
      | "ANALYZING"
      | "COMPLETED"
      | "FAILED"
      | "REQUIRES_REVIEW"
      | "REVIEWED";
    /** ImpactItemResponse */
    ImpactItemResponse: {
      /** Obligation Id */
      obligation_id?: string | null;
      entity_type: components["schemas"]["EntityType"];
      /** Entity Id */
      entity_id: string;
      impact_level: components["schemas"]["ImpactLevel"];
      /** Confidence */
      confidence: number;
      /** Match Score */
      match_score: number;
      /** Reason */
      reason: string;
      /** Evidence */
      evidence?: string | null;
      /**
       * Status
       * @default ACTIVE
       */
      status: string;
      /** Id */
      id: string;
      /** Impact Assessment Id */
      impact_assessment_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at?: string | null;
    };
    /**
     * ImpactLevel
     * @enum {string}
     */
    ImpactLevel:
      | "NO_MATCH"
      | "LOW"
      | "MEDIUM"
      | "HIGH"
      | "POTENTIALLY_AFFECTED"
      | "REQUIRES_REVIEW";
    /** ImpactReportCreate */
    ImpactReportCreate: {
      /** Impact Assessment Id */
      impact_assessment_id: string;
      /** Title */
      title?: string | null;
    };
    /** ImpactReportResponse */
    ImpactReportResponse: {
      /** Id */
      id: string;
      /** Organization Id */
      organization_id: string;
      /** Impact Assessment Id */
      impact_assessment_id: string;
      /** Regulatory Change Id */
      regulatory_change_id: string;
      /** Title */
      title: string;
      /** Summary */
      summary?: string | null;
      status: components["schemas"]["ImpactReportStatus"];
      /** Version */
      version: number;
      /** Report Data */
      report_data: unknown;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at?: string | null;
    };
    /**
     * ImpactReportStatus
     * @enum {string}
     */
    ImpactReportStatus: "DRAFT" | "GENERATED" | "UNDER_REVIEW" | "REVIEWED" | "ARCHIVED";
    /** IngestionRunResponse */
    IngestionRunResponse: {
      status: components["schemas"]["IngestionStatus"];
      /**
       * Documents Discovered
       * @default 0
       */
      documents_discovered: number;
      /**
       * Documents Downloaded
       * @default 0
       */
      documents_downloaded: number;
      /**
       * Documents Processed
       * @default 0
       */
      documents_processed: number;
      /**
       * Documents Failed
       * @default 0
       */
      documents_failed: number;
      /** Error */
      error?: string | null;
      /** Id */
      id: string;
      /** Source Id */
      source_id: string;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /** Completed At */
      completed_at?: string | null;
    };
    /**
     * IngestionStatus
     * @enum {string}
     */
    IngestionStatus: "QUEUED" | "RUNNING" | "COMPLETED" | "PARTIAL" | "FAILED";
    /** MarketCreate */
    MarketCreate: {
      /** Name */
      name: string;
      /** Country */
      country: string;
      /** Region */
      region?: string | null;
      /** Regulatory Jurisdiction */
      regulatory_jurisdiction?: string | null;
      /** @default ACTIVE */
      status: components["schemas"]["MarketStatus"];
    };
    /** MarketResponse */
    MarketResponse: {
      /** Name */
      name: string;
      /** Country */
      country: string;
      /** Region */
      region?: string | null;
      /** Regulatory Jurisdiction */
      regulatory_jurisdiction?: string | null;
      /** @default ACTIVE */
      status: components["schemas"]["MarketStatus"];
      /** Id */
      id: string;
      /** Organization Id */
      organization_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * MarketStatus
     * @enum {string}
     */
    MarketStatus: "ACTIVE" | "INACTIVE" | "PLANNED";
    /** MarketUpdate */
    MarketUpdate: {
      /** Name */
      name?: string | null;
      /** Country */
      country?: string | null;
      /** Region */
      region?: string | null;
      /** Regulatory Jurisdiction */
      regulatory_jurisdiction?: string | null;
      status?: components["schemas"]["MarketStatus"] | null;
    };
    /** OrganizationCreate */
    OrganizationCreate: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Industry */
      industry?: string | null;
      /** Description */
      description?: string | null;
    };
    /** ProcessCreate */
    ProcessCreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Category */
      category?: string | null;
    };
    /** ProcessResponse */
    ProcessResponse: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Category */
      category?: string | null;
      /** Id */
      id: string;
      /** Organization Id */
      organization_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ProcessUpdate */
    ProcessUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Category */
      category?: string | null;
    };
    /** ProductCreate */
    ProductCreate: {
      /** Name */
      name: string;
      /** Product Code */
      product_code: string;
      /** Description */
      description?: string | null;
      /** Category */
      category?: string | null;
      /** Sub Category */
      sub_category?: string | null;
      /** @default ACTIVE */
      status: components["schemas"]["ProductStatus"];
      /** Regulatory Class */
      regulatory_class?: string | null;
      /** Keywords */
      keywords?: string | null;
    };
    /** ProductResponse */
    ProductResponse: {
      /** Name */
      name: string;
      /** Product Code */
      product_code: string;
      /** Description */
      description?: string | null;
      /** Category */
      category?: string | null;
      /** Sub Category */
      sub_category?: string | null;
      /** @default ACTIVE */
      status: components["schemas"]["ProductStatus"];
      /** Regulatory Class */
      regulatory_class?: string | null;
      /** Keywords */
      keywords?: string | null;
      /** Id */
      id: string;
      /** Organization Id */
      organization_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ProductStatus
     * @enum {string}
     */
    ProductStatus: "ACTIVE" | "INACTIVE" | "ARCHIVED" | "DRAFT";
    /** ProductUpdate */
    ProductUpdate: {
      /** Name */
      name?: string | null;
      /** Product Code */
      product_code?: string | null;
      /** Description */
      description?: string | null;
      /** Category */
      category?: string | null;
      /** Sub Category */
      sub_category?: string | null;
      status?: components["schemas"]["ProductStatus"] | null;
      /** Regulatory Class */
      regulatory_class?: string | null;
      /** Keywords */
      keywords?: string | null;
    };
    /** RegistrationCreate */
    RegistrationCreate: {
      /** Product Id */
      product_id: string;
      /** Market Id */
      market_id: string;
      /** Authority Id */
      authority_id: string;
      /** Registration Number */
      registration_number?: string | null;
      /** @default PENDING */
      status: components["schemas"]["RegistrationStatus"];
      /** Valid From */
      valid_from?: string | null;
      /** Valid Until */
      valid_until?: string | null;
      /** Metadata */
      metadata?: string | null;
    };
    /** RegistrationResponse */
    RegistrationResponse: {
      /** Product Id */
      product_id: string;
      /** Market Id */
      market_id: string;
      /** Authority Id */
      authority_id: string;
      /** Registration Number */
      registration_number?: string | null;
      /** @default PENDING */
      status: components["schemas"]["RegistrationStatus"];
      /** Valid From */
      valid_from?: string | null;
      /** Valid Until */
      valid_until?: string | null;
      /** Metadata */
      metadata?: string | null;
      /** Id */
      id: string;
      /** Organization Id */
      organization_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * RegistrationStatus
     * @enum {string}
     */
    RegistrationStatus: "ACTIVE" | "EXPIRED" | "PENDING" | "REJECTED" | "WITHDRAWN";
    /** RegistrationUpdate */
    RegistrationUpdate: {
      /** Product Id */
      product_id?: string | null;
      /** Market Id */
      market_id?: string | null;
      /** Authority Id */
      authority_id?: string | null;
      /** Registration Number */
      registration_number?: string | null;
      status?: components["schemas"]["RegistrationStatus"] | null;
      /** Valid From */
      valid_from?: string | null;
      /** Valid Until */
      valid_until?: string | null;
      /** Metadata */
      metadata?: string | null;
    };
    /** SourceCreate */
    SourceCreate: {
      /** Authority Id */
      authority_id: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Jurisdiction */
      jurisdiction?: string | null;
      /** Country */
      country?: string | null;
      source_type: components["schemas"]["SourceType"];
      connector_type: components["schemas"]["ConnectorType"];
      /** Url */
      url?: string | null;
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /** Schedule */
      schedule?: string | null;
    };
    /** SourceResponse */
    SourceResponse: {
      /** Authority Id */
      authority_id: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Jurisdiction */
      jurisdiction?: string | null;
      /** Country */
      country?: string | null;
      source_type: components["schemas"]["SourceType"];
      connector_type: components["schemas"]["ConnectorType"];
      /** Url */
      url?: string | null;
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /** Schedule */
      schedule?: string | null;
      /** Id */
      id: string;
      /** Last Run At */
      last_run_at?: string | null;
      /** Last Success At */
      last_success_at?: string | null;
      /** Last Error */
      last_error?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * SourceType
     * @enum {string}
     */
    SourceType: "RSS" | "API" | "WEB_SERVICE" | "HTML" | "DOCUMENT";
    /** SourceUpdate */
    SourceUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Jurisdiction */
      jurisdiction?: string | null;
      /** Country */
      country?: string | null;
      source_type?: components["schemas"]["SourceType"] | null;
      connector_type?: components["schemas"]["ConnectorType"] | null;
      /** Url */
      url?: string | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Schedule */
      schedule?: string | null;
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      user: components["schemas"]["UserResponse"];
    };
    /** UserCreate */
    UserCreate: {
      /** Name */
      name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** @default VIEWER */
      role: components["schemas"]["UserRole"];
    };
    /** UserResponse */
    UserResponse: {
      /** Id */
      id: string;
      /** Organization Id */
      organization_id: string;
      /** Name */
      name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      role: components["schemas"]["UserRole"];
      /** Is Active */
      is_active: boolean;
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole:
      | "ADMIN"
      | "REGULATORY_MANAGER"
      | "COMPLIANCE_MANAGER"
      | "REVIEWER"
      | "ANALYST"
      | "VIEWER";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_register_api_v1_auth_register_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  list_authorities_api_v1_regulatory_authorities__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthorityResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_authority_api_v1_regulatory_authorities__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthorityCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthorityResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_authority_api_v1_regulatory_authorities__authority_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        authority_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthorityResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_authority_api_v1_regulatory_authorities__authority_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        authority_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_authority_api_v1_regulatory_authorities__authority_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        authority_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthorityUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthorityResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_sources_api_v1_regulatory_sources__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        authority_id?: string | null;
        enabled?: boolean | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_source_api_v1_regulatory_sources__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_source_api_v1_regulatory_sources__source_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_source_api_v1_regulatory_sources__source_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_source_api_v1_regulatory_sources__source_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_source_api_v1_regulatory_sources__source_id__run_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestionRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_source_runs_api_v1_regulatory_sources__source_id__runs_get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestionRunResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_api_v1_regulatory_sources_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestionRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_document_api_v1_regulatory_documents_upload_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_regulatory_documents_upload_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentUploadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  trigger_document_processing_api_v1_regulatory_documents__document_id__process_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_document_status_api_v1_regulatory_documents__document_id__status_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_documents_api_v1_regulatory_documents__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_document_api_v1_regulatory_documents__document_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_products_api_v1_portfolio_products__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        status?: components["schemas"]["ProductStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_product_api_v1_portfolio_products__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_product_api_v1_portfolio_products__product_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_product_api_v1_portfolio_products__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_product_api_v1_portfolio_products__product_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_markets_api_v1_portfolio_markets__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        status?: components["schemas"]["MarketStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MarketResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_market_api_v1_portfolio_markets__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MarketCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MarketResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_market_api_v1_portfolio_markets__market_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        market_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MarketResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_market_api_v1_portfolio_markets__market_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        market_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_market_api_v1_portfolio_markets__market_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        market_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MarketUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MarketResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_processes_api_v1_portfolio_processes__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcessResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_process_api_v1_portfolio_processes__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcessCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_process_api_v1_portfolio_processes__process_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        process_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_process_api_v1_portfolio_processes__process_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        process_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_process_api_v1_portfolio_processes__process_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        process_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcessUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_controls_api_v1_portfolio_controls__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        category?: components["schemas"]["ControlCategory"] | null;
        status?: components["schemas"]["ControlStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ControlResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_control_api_v1_portfolio_controls__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ControlCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ControlResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_control_api_v1_portfolio_controls__control_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        control_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ControlResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_control_api_v1_portfolio_controls__control_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        control_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_control_api_v1_portfolio_controls__control_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        control_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ControlUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ControlResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_registrations_api_v1_portfolio_registrations__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        status?: components["schemas"]["RegistrationStatus"] | null;
        product_id?: string | null;
        market_id?: string | null;
        authority_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegistrationResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_registration_api_v1_portfolio_registrations__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegistrationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegistrationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_registration_api_v1_portfolio_registrations__registration_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        registration_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegistrationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_registration_api_v1_portfolio_registrations__registration_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        registration_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_registration_api_v1_portfolio_registrations__registration_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        registration_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegistrationUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegistrationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  analyze_impact_api_v1_impact_analyze_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImpactAssessmentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImpactAssessmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_impact_assessments_api_v1_impact__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        regulatory_change_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImpactAssessmentResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_impact_assessment_api_v1_impact__assessment_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImpactAssessmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_assessment_items_api_v1_impact__assessment_id__items_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImpactItemResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reanalyze_impact_api_v1_impact__assessment_id__reanalyze_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImpactAssessmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_report_api_v1_reports_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImpactReportCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImpactReportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_reports_api_v1_reports__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImpactReportResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_report_api_v1_reports__report_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        report_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImpactReportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_report_versions_api_v1_reports__report_id__versions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        report_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImpactReportResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  readiness_check_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  liveness_check_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
